-- DetaurBar_Data.lua
-- Handles data storage, list management, and completion states.
-- ItemDatabase is now in DetaurBar_ItemDB.lua (generated by parse_itemcache.py)

-- Global namespace
DetaurBar = DetaurBar or {}
DetaurBar.Data = {}

-- Helper to shift time by 3 hours so that midnight of shifted time is 3:00 AM of actual time
local function GetLogicalDay(timestamp)
    local shiftedTime = (timestamp or time()) - 10800
    return date("%Y-%m-%d", shiftedTime)
end

function DetaurBar.Data.InitializeDB()
    if not DetaurBarDB then
        DetaurBarDB = {}
    end
    if DetaurBarDB.tasks and not DetaurBarDB.todo then
        DetaurBarDB.todo = { day = DetaurBarDB.tasks, week = {}, month = {} }
        DetaurBarDB.tasks = nil
    end
    if not DetaurBarDB.todo then
        DetaurBarDB.todo = {}
    end
    if not DetaurBarDB.todo.day then DetaurBarDB.todo.day = {} end
    if not DetaurBarDB.todo.week then DetaurBarDB.todo.week = {} end
    if not DetaurBarDB.todo.month then DetaurBarDB.todo.month = {} end
    if not DetaurBarDB.notes then
        DetaurBarDB.notes = {
            categories = { "General", "War", "Guild" },
            data = {
                ["General"] = {},
                ["War"] = {},
                ["Guild"] = {},
            }
        }
    elseif DetaurBarDB.notes.war or DetaurBarDB.notes.general or DetaurBarDB.notes.guild then
        local oldData = {}
        if DetaurBarDB.notes.general then oldData["General"] = DetaurBarDB.notes.general end
        if DetaurBarDB.notes.war then oldData["War"] = DetaurBarDB.notes.war end
        if DetaurBarDB.notes.guild then oldData["Guild"] = DetaurBarDB.notes.guild end
        DetaurBarDB.notes = {
            categories = { "General", "War", "Guild" },
            data = oldData,
        }
    elseif not DetaurBarDB.notes.categories then
        DetaurBarDB.notes.categories = { "General", "War", "Guild" }
        DetaurBarDB.notes.data = DetaurBarDB.notes.data or {}
        for _, name in ipairs(DetaurBarDB.notes.categories) do
            if not DetaurBarDB.notes.data[name] then DetaurBarDB.notes.data[name] = {} end
        end
    end
    if DetaurBarDB.buy and not DetaurBarDB.loot then
        DetaurBarDB.loot = DetaurBarDB.buy
        DetaurBarDB.buy = nil
    end
    if DetaurBarDB.loot and DetaurBarDB.loot[1] then
        DetaurBarDB.loot = { add = DetaurBarDB.loot, delete = {} }
    elseif DetaurBarDB.loot and not DetaurBarDB.loot.add then
        DetaurBarDB.loot = { add = {}, delete = {} }
    end
    if not DetaurBarDB.loot then
        DetaurBarDB.loot = { add = {}, refuse = {} }
    end
    if not DetaurBarDB.loot.add then DetaurBarDB.loot.add = {} end
    if not DetaurBarDB.loot.delete then DetaurBarDB.loot.delete = {} end
    if DetaurBarDB.loot.deleteAllGrays == nil then DetaurBarDB.loot.deleteAllGrays = false end
    if not DetaurBarDB.sell then
        DetaurBarDB.sell = {}
    end
    if not DetaurBarDB.price then
        DetaurBarDB.price = {}
    end
    if not DetaurBarDB.priceHistory then
        DetaurBarDB.priceHistory = {}
    end
    if not DetaurBarDB.settings then
        DetaurBarDB.settings = {}
    end
    if DetaurBarDB.settings.dungeonFlashEnabled == nil then
        DetaurBarDB.settings.dungeonFlashEnabled = false
    end
    if not DetaurBarDB.settings.dungeonFlashColor then
        DetaurBarDB.settings.dungeonFlashColor = "YELLOW"
    end
    if DetaurBarDB.settings.dungeonFlashDuration == nil then
        DetaurBarDB.settings.dungeonFlashDuration = 0
    end
    if not DetaurBarDB.settings.ahScanInterval then
        DetaurBarDB.settings.ahScanInterval = 10
    end
    if DetaurBarDB.settings.wgAlertsEnabled == nil then
        DetaurBarDB.settings.wgAlertsEnabled = false
    end
    if not DetaurBarDB.settings.wgAlert1Minutes then
        DetaurBarDB.settings.wgAlert1Minutes = 15
    end
    if not DetaurBarDB.settings.wgAlert1Duration then
        DetaurBarDB.settings.wgAlert1Duration = 2
    end
    if not DetaurBarDB.settings.wgAlert1Color then
        DetaurBarDB.settings.wgAlert1Color = "YELLOW"
    end
    if DetaurBarDB.settings.wgAlert1PlaySound == nil then
        DetaurBarDB.settings.wgAlert1PlaySound = false
    end
    if not DetaurBarDB.settings.wgAlert1Sound then
        DetaurBarDB.settings.wgAlert1Sound = "RaidWarning"
    end
    if not DetaurBarDB.settings.wgAlert2Duration then
        DetaurBarDB.settings.wgAlert2Duration = 0
    end
    if not DetaurBarDB.settings.wgAlert2Color then
        DetaurBarDB.settings.wgAlert2Color = "YELLOW"
    end
    if not DetaurBarDB.settings.wgAlert2Minutes then
        DetaurBarDB.settings.wgAlert2Minutes = 1
    end
    if DetaurBarDB.settings.wgAlert2PlaySound == nil then
        DetaurBarDB.settings.wgAlert2PlaySound = true
    end
    if not DetaurBarDB.settings.wgAlert2Sound then
        DetaurBarDB.settings.wgAlert2Sound = "RaidWarning"
    end
    if not DetaurBarDB.settings.wgCycleOffset then
        DetaurBarDB.settings.wgCycleOffset = nil
    end
    if DetaurBarDB.settings.randomAlertsEnabled == nil then
        DetaurBarDB.settings.randomAlertsEnabled = false
    end
    if not DetaurBarDB.settings.randomAlerts then
        DetaurBarDB.settings.randomAlerts = {}
    end
    if not DetaurBarDB.settings.randomActiveAlertId then
        DetaurBarDB.settings.randomActiveAlertId = nil
    end
    if DetaurBarDB.settings.enemyEnabled == nil then
        DetaurBarDB.settings.enemyEnabled = false
    end
    if DetaurBarDB.settings.enemyFlashEnabled == nil then
        DetaurBarDB.settings.enemyFlashEnabled = false
    end
    if not DetaurBarDB.settings.enemyFlashColor then
        DetaurBarDB.settings.enemyFlashColor = "YELLOW"
    end
    if DetaurBarDB.settings.enemyPlaySound == nil then
        DetaurBarDB.settings.enemyPlaySound = false
    end
    if not DetaurBarDB.settings.enemySound then
        DetaurBarDB.settings.enemySound = "RaidWarning"
    end
    if not DetaurBarDB.settings.enemyFlashStyle then
        DetaurBarDB.settings.enemyFlashStyle = "AGGRESSIVE"
    end
    if not DetaurBarDB.minimapAngle then
        DetaurBarDB.minimapAngle = 45
    end

    if not DetaurBar.Data.ItemDatabaseReverse then
        DetaurBar.Data.ItemDatabaseReverse = {}
        for name, id in pairs(DetaurBar.Data.ItemDatabase) do
            DetaurBar.Data.ItemDatabaseReverse[id] = name
        end
    end

    local currentDay = GetLogicalDay(time())
    if not DetaurBarDB.iconCache then
        DetaurBarDB.iconCache = {}
    end

    if not DetaurBarDB.lastResetDay then
        DetaurBarDB.lastResetDay = currentDay
    elseif DetaurBarDB.lastResetDay ~= currentDay then
        DetaurBarDB.lastResetDay = currentDay
        for _, task in ipairs(DetaurBarDB.todo.day) do
            task.completed = false
        end
    end
end

function DetaurBar.Data.GetItems(category)
    DetaurBar.Data.InitializeDB()
    if category == "todo_day" then
        return DetaurBarDB.todo.day
    elseif category == "todo_week" then
        return DetaurBarDB.todo.week
    elseif category == "todo_month" then
        return DetaurBarDB.todo.month
    elseif category:find("^notes_") then
        local catName = category:sub(7)
        for _, catDisplayName in ipairs(DetaurBarDB.notes.categories) do
            if catDisplayName:lower() == catName then
                return DetaurBarDB.notes.data[catDisplayName] or {}
            end
        end
        return {}
    elseif category == "loot_add" then
        return DetaurBarDB.loot.add
    elseif category == "loot_delete" then
        return DetaurBarDB.loot.delete
    elseif category == "sell" then
        return DetaurBarDB.sell
    elseif category == "price" then
        local faction = UnitFactionGroup("player") or "Unknown"
        if not DetaurBarDB.price[faction] then
            DetaurBarDB.price[faction] = {}
        end
        return DetaurBarDB.price[faction]
    end
    return {}
end

function DetaurBar.Data.AddItem(category, title, subCategory)
    DetaurBar.Data.InitializeDB()
    local items = DetaurBar.Data.GetItems(category)

    local newItem = {
        id = time() .. "_" .. tostring(math.random(1000, 9999)),
        title = title,
        completed = false,
        created = time(),
        subCategory = subCategory
    }

    table.insert(items, newItem)
    return newItem
end

function DetaurBar.Data.DeleteItem(category, id)
    DetaurBar.Data.InitializeDB()
    local items = DetaurBar.Data.GetItems(category)

    for i, item in ipairs(items) do
        if item.id == id then
            table.remove(items, i)
            return true
        end
    end
    return false
end

function DetaurBar.Data.ToggleTask(category, id)
    DetaurBar.Data.InitializeDB()
    local items = DetaurBar.Data.GetItems(category)
    for _, item in ipairs(items) do
        if item.id == id then
            item.completed = not item.completed
            return item.completed
        end
    end
    return nil
end

function DetaurBar.Data.GetItemById(category, id)
    DetaurBar.Data.InitializeDB()
    local items = DetaurBar.Data.GetItems(category)
    for _, item in ipairs(items) do
        if item.id == id then
            return item
        end
    end
    return nil
end

function DetaurBar.Data.MoveItem(fromCategory, toCategory, id)
    DetaurBar.Data.InitializeDB()
    local fromList = DetaurBar.Data.GetItems(fromCategory)
    local toList = DetaurBar.Data.GetItems(toCategory)

    for i, item in ipairs(fromList) do
        if item.id == id then
            local movingItem = table.remove(fromList, i)
            movingItem.completed = false
            table.insert(toList, movingItem)
            return true
        end
    end
    return false
end

function DetaurBar.Data.SavePricePoint(itemId, buyoutPerItem)
    DetaurBar.Data.InitializeDB()
    local faction = UnitFactionGroup("player") or "Unknown"
    local key = itemId .. ":" .. faction
    if not DetaurBarDB.priceHistory[key] then
        DetaurBarDB.priceHistory[key] = {}
    end
    DetaurBarDB.priceHistory[key][tostring(time())] = buyoutPerItem
end

function DetaurBar.Data.GetPriceHistory(itemId)
    DetaurBar.Data.InitializeDB()
    local faction = UnitFactionGroup("player") or "Unknown"
    local key = itemId .. ":" .. faction
    return DetaurBarDB.priceHistory[key] or {}
end

function DetaurBar.Data.GetSettings()
    DetaurBar.Data.InitializeDB()
    return DetaurBarDB.settings
end

function DetaurBar.Data.GetItemName(itemId)
    if not itemId then return nil end
    if DetaurBar.Data.ItemDatabaseReverse and DetaurBar.Data.ItemDatabaseReverse[itemId] then
        local name = DetaurBar.Data.ItemDatabaseReverse[itemId]
        return (name:sub(1,1):upper() .. name:sub(2)):gsub("(%s)(%a)", function(s, a) return s .. a:upper() end)
    end
    return (GetItemInfo(itemId))
end

-- Icon caching: tries static ItemIcons -> DetaurBarDB.iconCache -> GetItemInfo
-- If GetItemInfo succeeds, stores result in DB for next reload.
function DetaurBar.Data.GetItemTexture(itemId)
    if not itemId then return nil end
    if DetaurBar.Data.ItemIcons and DetaurBar.Data.ItemIcons[itemId] then
        return DetaurBar.Data.ItemIcons[itemId]
    end
    DetaurBar.Data.InitializeDB()
    if DetaurBarDB.iconCache and DetaurBarDB.iconCache[itemId] then
        return DetaurBarDB.iconCache[itemId]
    end
    local texture = select(10, GetItemInfo(itemId))
    if texture then
        if not DetaurBarDB.iconCache then DetaurBarDB.iconCache = {} end
        DetaurBarDB.iconCache[itemId] = texture
    end
    return texture
end

function DetaurBar.Data.GetRandomAlerts()
    DetaurBar.Data.InitializeDB()
    return DetaurBarDB.settings.randomAlerts or {}
end

function DetaurBar.Data.AddRandomAlert(name)
    DetaurBar.Data.InitializeDB()
    local alert = {
        id = tostring(time()) .. "_" .. tostring(math.random(1000, 9999)),
        name = name or "New Alert",
        intervalMinutes = 5,
        flashDuration = 3,
        flashColor = "YELLOW",
        playSound = false,
        sound = "RaidWarning",
    }
    table.insert(DetaurBarDB.settings.randomAlerts, alert)
    return alert
end

function DetaurBar.Data.DeleteRandomAlert(id)
    DetaurBar.Data.InitializeDB()
    local alerts = DetaurBarDB.settings.randomAlerts
    for i, alert in ipairs(alerts) do
        if alert.id == id then
            table.remove(alerts, i)
            if DetaurBarDB.settings.randomActiveAlertId == id then
                DetaurBarDB.settings.randomActiveAlertId = alerts[1] and alerts[1].id or nil
            end
            return true
        end
    end
    return false
end

function DetaurBar.Data.GetRandomActiveAlert()
    DetaurBar.Data.InitializeDB()
    local id = DetaurBarDB.settings.randomActiveAlertId
    if not id then return nil end
    for _, alert in ipairs(DetaurBarDB.settings.randomAlerts) do
        if alert.id == id then return alert end
    end
    return nil
end

function DetaurBar.Data.SetRandomActiveAlert(id)
    DetaurBar.Data.InitializeDB()
    DetaurBarDB.settings.randomActiveAlertId = id
end

function DetaurBar.Data.GetNoteCategories()
    DetaurBar.Data.InitializeDB()
    return DetaurBarDB.notes.categories
end

function DetaurBar.Data.NoteCategoryExists(name)
    DetaurBar.Data.InitializeDB()
    if not name then return false end
    for _, cat in ipairs(DetaurBarDB.notes.categories) do
        if cat == name then return true end
    end
    return false
end

function DetaurBar.Data.AddNoteCategory(name)
    DetaurBar.Data.InitializeDB()
    name = name:gsub("^%s*(.-)%s*$", "%1")
    if name == "" then return nil end
    for _, cat in ipairs(DetaurBarDB.notes.categories) do
        if cat:lower() == name:lower() then return nil end
    end
    table.insert(DetaurBarDB.notes.categories, name)
    DetaurBarDB.notes.data[name] = {}
    return name
end

function DetaurBar.Data.DeleteNoteCategory(name)
    DetaurBar.Data.InitializeDB()
    if #DetaurBarDB.notes.categories <= 1 then return false end
    for i, cat in ipairs(DetaurBarDB.notes.categories) do
        if cat == name then
            table.remove(DetaurBarDB.notes.categories, i)
            DetaurBarDB.notes.data[name] = nil
            return true
        end
    end
    return false
end
