-- DetaurBar_Data.lua
-- Handles data storage, list management, and completion states.
-- ItemDatabase is now in DetaurBar_ItemDB.lua (generated by parse_itemcache.py)

-- Global namespace
DetaurBar = DetaurBar or {}
DetaurBar.Data = {}

-- Helper to shift time by 3 hours so that midnight of shifted time is 3:00 AM of actual time
local function GetLogicalDay(timestamp)
    local shiftedTime = (timestamp or time()) - 10800
    return date("%Y-%m-%d", shiftedTime)
end

function DetaurBar.Data.InitializeDB()
    if not DetaurBarDB then
        DetaurBarDB = {}
    end
    if not DetaurBarDB.todo then
        DetaurBarDB.todo = {}
    end
    if not DetaurBarDB.todo.day then DetaurBarDB.todo.day = {} end
    if not DetaurBarDB.todo.week then DetaurBarDB.todo.week = {} end
    if not DetaurBarDB.todo.month then DetaurBarDB.todo.month = {} end
    if not DetaurBarDB.tasks then
        DetaurBarDB.tasks = {
            categories = { "General" },
            data = {
                ["General"] = {},
            }
        }
    elseif not DetaurBarDB.tasks.categories then
        DetaurBarDB.tasks.categories = { "General" }
        DetaurBarDB.tasks.data = DetaurBarDB.tasks.data or {}
        for _, name in ipairs(DetaurBarDB.tasks.categories) do
            if not DetaurBarDB.tasks.data[name] then DetaurBarDB.tasks.data[name] = {} end
        end
    end
    if not DetaurBarDB.notes then
        DetaurBarDB.notes = {
            categories = { "General", "War", "Guild" },
            data = {
                ["General"] = {},
                ["War"] = {},
                ["Guild"] = {},
            }
        }
    elseif DetaurBarDB.notes.war or DetaurBarDB.notes.general or DetaurBarDB.notes.guild then
        local oldData = {}
        if DetaurBarDB.notes.general then oldData["General"] = DetaurBarDB.notes.general end
        if DetaurBarDB.notes.war then oldData["War"] = DetaurBarDB.notes.war end
        if DetaurBarDB.notes.guild then oldData["Guild"] = DetaurBarDB.notes.guild end
        DetaurBarDB.notes = {
            categories = { "General", "War", "Guild" },
            data = oldData,
        }
    elseif not DetaurBarDB.notes.categories then
        DetaurBarDB.notes.categories = { "General", "War", "Guild" }
        DetaurBarDB.notes.data = DetaurBarDB.notes.data or {}
        for _, name in ipairs(DetaurBarDB.notes.categories) do
            if not DetaurBarDB.notes.data[name] then DetaurBarDB.notes.data[name] = {} end
        end
    end
    if DetaurBarDB.buy and not DetaurBarDB.loot then
        DetaurBarDB.loot = DetaurBarDB.buy
        DetaurBarDB.buy = nil
    end
    if DetaurBarDB.loot and DetaurBarDB.loot[1] then
        DetaurBarDB.loot = { add = DetaurBarDB.loot, delete = {} }
    elseif DetaurBarDB.loot and not DetaurBarDB.loot.add then
        DetaurBarDB.loot = { add = {}, delete = {} }
    end
    if not DetaurBarDB.loot then
        DetaurBarDB.loot = { add = {}, refuse = {} }
    end
    if not DetaurBarDB.loot.add then DetaurBarDB.loot.add = {} end
    if not DetaurBarDB.loot.delete then DetaurBarDB.loot.delete = {} end
    if DetaurBarDB.loot.deleteAllGrays == nil then DetaurBarDB.loot.deleteAllGrays = false end
    if not DetaurBarDB.sell then
        DetaurBarDB.sell = {}
    end
    if not DetaurBarDB.price then
        DetaurBarDB.price = {}
    end
    if not DetaurBarDB.recipes then
        DetaurBarDB.recipes = {}
    end
    -- [MIGRATION 2026-07-06] Convert old array-format price to faction-based format
    -- Old: DetaurBarDB.price = { {title=...}, {title=...}, ["Horde"]={} }
    -- New: DetaurBarDB.price = { ["Horde"] = { {title=...}, {title=...} } }
    if DetaurBarDB.price[1] then
        local faction = UnitFactionGroup("player") or "Horde"
        local items = {}
        local i = 1
        while type(DetaurBarDB.price[i]) == "table" do
            table.insert(items, DetaurBarDB.price[i])
            DetaurBarDB.price[i] = nil
            i = i + 1
        end
        DetaurBarDB.price[faction] = items
        for k, v in pairs(DetaurBarDB.price) do
            if type(k) ~= "string" then
                DetaurBarDB.price[k] = nil
            end
        end
        if not DetaurBarDB.price[faction] then
            DetaurBarDB.price[faction] = {}
        end
    end
    if not DetaurBarDB.priceHistory then
        DetaurBarDB.priceHistory = {}
    end
    if not DetaurBarDB.buySellHistory then
        DetaurBarDB.buySellHistory = {}
    end
    if not DetaurBarDB.priceLists then
        DetaurBarDB.priceLists = { ["Default"] = true }
    else
        DetaurBarDB.priceLists["All"] = nil
        DetaurBarDB.priceLists["Default"] = true
        for _, factionItems in pairs(DetaurBarDB.price) do
            if type(factionItems) == "table" then
                for _, item in ipairs(factionItems) do
                    if item.list == "All" then item.list = nil end
                end
            end
        end
    end
    if not DetaurBarDB.settings then
        DetaurBarDB.settings = {}
    end
    if DetaurBarDB.settings.dungeonFlashEnabled == nil then
        DetaurBarDB.settings.dungeonFlashEnabled = false
    end
    if not DetaurBarDB.settings.dungeonFlashColor then
        DetaurBarDB.settings.dungeonFlashColor = "YELLOW"
    end
    if DetaurBarDB.settings.dungeonFlashDuration == nil then
        DetaurBarDB.settings.dungeonFlashDuration = 0
    end
    if not DetaurBarDB.settings.bankThreshold then
        DetaurBarDB.settings.bankThreshold = 30
    end
    if not DetaurBarDB.settings.bankSources then
        DetaurBarDB.settings.bankSources = { Personal = true, Bank = true, Guildbank = true }
    end
    if DetaurBarDB.settings.chartGraphVisible == nil then
        DetaurBarDB.settings.chartGraphVisible = true
    end
    if DetaurBarDB.settings.chartThresholdVisible == nil then
        DetaurBarDB.settings.chartThresholdVisible = true
    end
    if DetaurBarDB.settings.chartOrderMode == nil then
        DetaurBarDB.settings.chartOrderMode = false
    end
    if DetaurBarDB.settings.chartBuySellVisible == nil then
        DetaurBarDB.settings.chartBuySellVisible = true
    end
    if not DetaurBarDB.settings.ahScanInterval then
        DetaurBarDB.settings.ahScanInterval = 10
    end
    if DetaurBarDB.settings.ahScanningEnabled == nil then
        DetaurBarDB.settings.ahScanningEnabled = true
    end
    if not DetaurBarDB.settings.scanEnabledLists then
        DetaurBarDB.settings.scanEnabledLists = { ["Default"] = true }
    end
    if DetaurBarDB.settings.wgAlertsEnabled == nil then
        DetaurBarDB.settings.wgAlertsEnabled = false
    end
    if DetaurBarDB.settings.wgShowTimeOnEnemyTracker == nil then
        DetaurBarDB.settings.wgShowTimeOnEnemyTracker = false
    end
    if not DetaurBarDB.settings.wgAlert1Minutes then
        DetaurBarDB.settings.wgAlert1Minutes = 15
    end
    if not DetaurBarDB.settings.wgAlert1Duration then
        DetaurBarDB.settings.wgAlert1Duration = 2
    end
    if not DetaurBarDB.settings.wgAlert1Color then
        DetaurBarDB.settings.wgAlert1Color = "YELLOW"
    end
    if DetaurBarDB.settings.wgAlert1PlaySound == nil then
        DetaurBarDB.settings.wgAlert1PlaySound = false
    end
    if not DetaurBarDB.settings.wgAlert1Sound then
        DetaurBarDB.settings.wgAlert1Sound = "RaidWarning"
    end
    if not DetaurBarDB.settings.wgAlert2Duration then
        DetaurBarDB.settings.wgAlert2Duration = 0
    end
    if not DetaurBarDB.settings.wgAlert2Color then
        DetaurBarDB.settings.wgAlert2Color = "YELLOW"
    end
    if not DetaurBarDB.settings.wgAlert2Minutes then
        DetaurBarDB.settings.wgAlert2Minutes = 1
    end
    if DetaurBarDB.settings.wgAlert2PlaySound == nil then
        DetaurBarDB.settings.wgAlert2PlaySound = true
    end
    if not DetaurBarDB.settings.wgAlert2Sound then
        DetaurBarDB.settings.wgAlert2Sound = "RaidWarning"
    end
    if not DetaurBarDB.settings.wgCycleOffset then
        DetaurBarDB.settings.wgCycleOffset = nil
    end
    if DetaurBarDB.settings.randomAlertsEnabled == nil then
        DetaurBarDB.settings.randomAlertsEnabled = false
    end
    if not DetaurBarDB.settings.randomAlerts then
        DetaurBarDB.settings.randomAlerts = {}
    end
    if not DetaurBarDB.settings.randomActiveAlertId then
        DetaurBarDB.settings.randomActiveAlertId = nil
    end
    if DetaurBarDB.settings.enemyEnabled == nil then
        DetaurBarDB.settings.enemyEnabled = false
    end
    if DetaurBarDB.settings.enemyShowCast == nil then
        DetaurBarDB.settings.enemyShowCast = true
    end
    if DetaurBarDB.settings.enemyFlashEnabled == nil then
        DetaurBarDB.settings.enemyFlashEnabled = false
    end
    if not DetaurBarDB.settings.enemyFlashColor then
        DetaurBarDB.settings.enemyFlashColor = "YELLOW"
    end
    if DetaurBarDB.settings.enemyPlaySound == nil then
        DetaurBarDB.settings.enemyPlaySound = false
    end
    if not DetaurBarDB.settings.enemySound then
        DetaurBarDB.settings.enemySound = "RaidWarning"
    end
    if not DetaurBarDB.settings.enemyFlashStyle then
        DetaurBarDB.settings.enemyFlashStyle = "AGGRESSIVE"
    end
    if DetaurBarDB.settings.raidRollAlertEnabled == nil then
        DetaurBarDB.settings.raidRollAlertEnabled = false
    end
    if not DetaurBarDB.settings.raidRollAlertColor then
        DetaurBarDB.settings.raidRollAlertColor = "YELLOW"
    end
    if DetaurBarDB.settings.raidRollAlertDuration == nil then
        DetaurBarDB.settings.raidRollAlertDuration = 0
    end
    if not DetaurBarDB.settings.raidRollAlertStyle then
        DetaurBarDB.settings.raidRollAlertStyle = "AGGRESSIVE"
    end
    if DetaurBarDB.settings.raidRollAlertPlaySound == nil then
        DetaurBarDB.settings.raidRollAlertPlaySound = false
    end
    if not DetaurBarDB.settings.raidRollAlertSound then
        DetaurBarDB.settings.raidRollAlertSound = "RaidWarning"
    end
    if DetaurBarDB.settings.raidReadyCheckAlertEnabled == nil then
        DetaurBarDB.settings.raidReadyCheckAlertEnabled = false
    end
    if not DetaurBarDB.settings.raidReadyCheckAlertColor then
        DetaurBarDB.settings.raidReadyCheckAlertColor = "YELLOW"
    end
    if DetaurBarDB.settings.raidReadyCheckAlertDuration == nil then
        DetaurBarDB.settings.raidReadyCheckAlertDuration = 0
    end
    if not DetaurBarDB.settings.raidReadyCheckAlertStyle then
        DetaurBarDB.settings.raidReadyCheckAlertStyle = "AGGRESSIVE"
    end
    if DetaurBarDB.settings.raidReadyCheckAlertPlaySound == nil then
        DetaurBarDB.settings.raidReadyCheckAlertPlaySound = false
    end
    if not DetaurBarDB.settings.raidReadyCheckAlertSound then
        DetaurBarDB.settings.raidReadyCheckAlertSound = "RaidWarning"
    end
    if not DetaurBarDB.settings.lootSubTabsVisible then
        DetaurBarDB.settings.lootSubTabsVisible = { ["Add"] = true, ["Delete"] = true }
    end
    if not DetaurBarDB.settings.priceSubTabsVisible then
        DetaurBarDB.settings.priceSubTabsVisible = { ["News"] = true, ["Chart"] = true, ["Bank"] = true, ["List"] = true, ["Recipes"] = true }
    end
    if not DetaurBarDB.settings.alertSubTabsVisible then
        DetaurBarDB.settings.alertSubTabsVisible = { ["Dung"] = true, ["Raid"] = true, ["WG"] = true, ["Random"] = true, ["Enemy"] = true, ["Buffs"] = true, ["Debuffs"] = true, ["Item"] = true, ["Arena"] = true }
    end
    if DetaurBarDB.settings.mindControlAlertEnabled == nil then
        DetaurBarDB.settings.mindControlAlertEnabled = false
    end
    if DetaurBarDB.settings.autoSellRepairEnabled == nil then
        DetaurBarDB.settings.autoSellRepairEnabled = false
    end
    if DetaurBarDB.settings.showAlertsInChat == nil then
        DetaurBarDB.settings.showAlertsInChat = false
    end
    if DetaurBarDB.settings.ignoreYellEnabled == nil then
        DetaurBarDB.settings.ignoreYellEnabled = false
    end
    if DetaurBarDB.settings.showArmorEnabled == nil then
        DetaurBarDB.settings.showArmorEnabled = false
    end
    if DetaurBarDB.settings.armorShowMail == nil then
        DetaurBarDB.settings.armorShowMail = true
    end
    if DetaurBarDB.settings.armorShowPlate == nil then
        DetaurBarDB.settings.armorShowPlate = true
    end
    if DetaurBarDB.settings.armorShowCloth == nil then
        DetaurBarDB.settings.armorShowCloth = true
    end
    if DetaurBarDB.settings.armorShowLeather == nil then
        DetaurBarDB.settings.armorShowLeather = true
    end
    if not DetaurBarDB.settings.armorIcons then
        DetaurBarDB.settings.armorIcons = {
            Mail = "Interface\\Icons\\INV_Chest_Chain_03",
            Plate = "Interface\\Icons\\INV_Chest_Plate03",
            Cloth = "Interface\\Icons\\INV_Chest_Cloth_06",
            Leather = "Interface\\Icons\\INV_Chest_Leather_04",
        }
    end
    if DetaurBarDB.settings.buffsEnabled == nil then
        DetaurBarDB.settings.buffsEnabled = false
    end
    if not DetaurBarDB.settings.buffsSpellSlots then
        DetaurBarDB.settings.buffsSpellSlots = {}
    end
    if DetaurBarDB.settings.arenaFlashEnabled == nil then
        DetaurBarDB.settings.arenaFlashEnabled = false
    end
    if not DetaurBarDB.settings.arenaFlashColor then
        DetaurBarDB.settings.arenaFlashColor = "YELLOW"
    end
    if DetaurBarDB.settings.arenaFlashDuration == nil then
        DetaurBarDB.settings.arenaFlashDuration = 0
    end
    if DetaurBarDB.settings.buffsFollowStacks == nil then
        DetaurBarDB.settings.buffsFollowStacks = false
    end
    if DetaurBarDB.settings.buffsDontHideUnused == nil then
        DetaurBarDB.settings.buffsDontHideUnused = false
    end
    if DetaurBarDB.settings.buffsHideTimeout == nil then
        DetaurBarDB.settings.buffsHideTimeout = 1
    end
    if not DetaurBarDB.settings.buffsItemCooldownSlots then
        DetaurBarDB.settings.buffsItemCooldownSlots = {}
    end
    if DetaurBarDB.settings.itemTrackingEnabled == nil then
        DetaurBarDB.settings.itemTrackingEnabled = false
    end
    if not DetaurBarDB.settings.itemTrackingSlots then
        DetaurBarDB.settings.itemTrackingSlots = {}
    end
    if DetaurBarDB.settings.itemTrackingInterval == nil then
        DetaurBarDB.settings.itemTrackingInterval = 30
    end
    if DetaurBarDB.settings.itemTrackingThreshold == nil then
        DetaurBarDB.settings.itemTrackingThreshold = 0
    end
    if DetaurBarDB.settings.debuffsEnabled == nil then
        DetaurBarDB.settings.debuffsEnabled = false
    end
    if DetaurBarDB.settings.debuffsShowEverything == nil then
        DetaurBarDB.settings.debuffsShowEverything = true
    end
    if not DetaurBarDB.settings.debuffsSlots then
        DetaurBarDB.settings.debuffsSlots = {}
    end
    if not DetaurBarDB.minimapAngle then
        DetaurBarDB.minimapAngle = 45
    end

    if not DetaurBar.Data.ItemDatabaseReverse then
        DetaurBar.Data.ItemDatabaseReverse = {}
        for name, id in pairs(DetaurBar.Data.ItemDatabase) do
            DetaurBar.Data.ItemDatabaseReverse[id] = name
        end
    end

    local currentDay = GetLogicalDay(time())
    if not DetaurBarDB.iconCache then
        DetaurBarDB.iconCache = {}
    end

    if not DetaurBarDB.lastResetDay then
        DetaurBarDB.lastResetDay = currentDay
    elseif DetaurBarDB.lastResetDay ~= currentDay then
        DetaurBarDB.lastResetDay = currentDay
        for _, task in ipairs(DetaurBarDB.todo.day) do
            task.completed = false
        end
        if DetaurBarDB.tasks and DetaurBarDB.tasks.data then
            for _, catName in ipairs(DetaurBarDB.tasks.categories) do
                local items = DetaurBarDB.tasks.data[catName]
                if items then
                    for _, item in ipairs(items) do
                        item.completed = false
                    end
                end
            end
        end
    end

    -- Clean up stale migration flags from previous buggy versions
    if DetaurBarDB._migratedHerbIds or DetaurBarDB._migratedHerbIdsV2 or DetaurBarDB._migratedHerbIdsV3 or DetaurBarDB._migratedHerbIdsFinal then
        DetaurBarDB._migratedHerbIds = nil
        DetaurBarDB._migratedHerbIdsV2 = nil
        DetaurBarDB._migratedHerbIdsV3 = nil
        DetaurBarDB._migratedHerbIdsFinal = nil
    end

    -- [MIGRATION 2026-07-06 v4] Fix shifted herb IDs in BOTH link items AND item:ID format.
    -- Warmane cache (2026-07): goldclover=36901, adder's tongue=36903, tiger lily=36904,
    -- lichbloom=36905, icethorn=36906, talandra's rose=36907, frost lotus=36908, fire leaf=39970
    -- Old WRONG DB had: frost lotus=36902, fire leaf=36903, adder's tongue=36905, lichbloom=36906, icethorn=36908
    local herbIdFix = {
        [36902] = 36908,  -- frost lotus
        [36903] = 39970,  -- fire leaf
        [36905] = 36903,  -- adder's tongue
        [36906] = 36905,  -- lichbloom
        [36908] = 36906,  -- icethorn
    }
    if not DetaurBarDB._migratedHerbIdsV4 then
        local function fixItemId(title)
            if title then
                -- Fix link format: |c...|Hitem:36908|h[Icethorn]|h|r  -> correct ID via name lookup
                local linkName = string.match(title, "%|h%[(.-)%]%|h")
                if linkName then
                    local cleaned = string.lower(linkName)
                    local correctId = DetaurBar.Data.ItemDatabase and DetaurBar.Data.ItemDatabase[cleaned]
                    if correctId then
                        local newTitle = string.gsub(title, "|Hitem:(%d+)", "|Hitem:" .. correctId)
                        if newTitle ~= title then
                            return newTitle
                        end
                    end
                end
                -- Fix item:ID format: "item:36902" -> "item:36908" via herbIdFix mapping
                local itemIdNum = tonumber(string.match(title, "^item:(%d+)$"))
                if itemIdNum and herbIdFix[itemIdNum] then
                    return "item:" .. herbIdFix[itemIdNum]
                end
            end
            return title
        end
        local function fixList(list)
            if list and type(list) == "table" then
                for _, item in ipairs(list) do
                    if item.title then
                        item.title = fixItemId(item.title)
                    end
                end
            end
        end
        fixList(DetaurBarDB.price)
        fixList(DetaurBarDB.sell)
        if DetaurBarDB.loot and type(DetaurBarDB.loot) == "table" then
            fixList(DetaurBarDB.loot.add)
            fixList(DetaurBarDB.loot.delete)
            fixList(DetaurBarDB.loot.refuse)
        end
        DetaurBarDB._migratedHerbIdsV4 = true
    end
end

function DetaurBar.Data.GetItems(category)
    DetaurBar.Data.InitializeDB()
    if category == "todo_day" then
        return DetaurBarDB.todo.day
    elseif category == "todo_week" then
        return DetaurBarDB.todo.week
    elseif category == "todo_month" then
        return DetaurBarDB.todo.month
    elseif category:find("^tasks_") then
        local catName = category:sub(7)
        for _, catDisplayName in ipairs(DetaurBarDB.tasks.categories) do
            if catDisplayName:lower() == catName then
                return DetaurBarDB.tasks.data[catDisplayName] or {}
            end
        end
        return {}
    elseif category:find("^notes_") then
        local catName = category:sub(7)
        for _, catDisplayName in ipairs(DetaurBarDB.notes.categories) do
            if catDisplayName:lower() == catName then
                return DetaurBarDB.notes.data[catDisplayName] or {}
            end
        end
        return {}
    elseif category == "loot_add" then
        return DetaurBarDB.loot.add
    elseif category == "loot_delete" then
        return DetaurBarDB.loot.delete
    elseif category == "sell" then
        return DetaurBarDB.sell
    elseif category == "price" then
        local faction = UnitFactionGroup("player") or "Unknown"
        if not DetaurBarDB.price[faction] then
            DetaurBarDB.price[faction] = {}
        end
        return DetaurBarDB.price[faction]
    elseif category == "recipes" then
        return DetaurBarDB.recipes
    end
    return {}
end

function DetaurBar.Data.AddItem(category, title, subCategory)
    DetaurBar.Data.InitializeDB()
    local items = DetaurBar.Data.GetItems(category)

    local newItem = {
        id = time() .. "_" .. tostring(math.random(1000, 9999)),
        title = title,
        completed = false,
        created = time(),
        subCategory = subCategory
    }

    table.insert(items, newItem)
    return newItem
end

function DetaurBar.Data.DeleteItem(category, id)
    DetaurBar.Data.InitializeDB()
    local items = DetaurBar.Data.GetItems(category)

    for i, item in ipairs(items) do
        if item.id == id then
            table.remove(items, i)
            return true
        end
    end
    return false
end

-- [RECIPES] AddRecipe — appends a recipe entry (with spellId, profession, reagents)
function DetaurBar.Data.AddRecipe(recipeData)
    DetaurBar.Data.InitializeDB()
    recipeData.id = recipeData.id or (time() .. "_" .. tostring(math.random(1000, 9999)))
    recipeData.created = recipeData.created or time()
    table.insert(DetaurBarDB.recipes, recipeData)
    return recipeData
end

-- [RECIPES] DeleteRecipe — removes recipe by id
function DetaurBar.Data.DeleteRecipe(id)
    DetaurBar.Data.InitializeDB()
    for i, recipe in ipairs(DetaurBarDB.recipes) do
        if recipe.id == id then
            table.remove(DetaurBarDB.recipes, i)
            return true
        end
    end
    return false
end

function DetaurBar.Data.ToggleTask(category, id)
    DetaurBar.Data.InitializeDB()
    local items = DetaurBar.Data.GetItems(category)
    for _, item in ipairs(items) do
        if item.id == id then
            item.completed = not item.completed
            return item.completed
        end
    end
    return nil
end

function DetaurBar.Data.GetItemById(category, id)
    DetaurBar.Data.InitializeDB()
    local items = DetaurBar.Data.GetItems(category)
    for _, item in ipairs(items) do
        if item.id == id then
            return item
        end
    end
    return nil
end

function DetaurBar.Data.MoveItem(fromCategory, toCategory, id)
    DetaurBar.Data.InitializeDB()
    local fromList = DetaurBar.Data.GetItems(fromCategory)
    local toList = DetaurBar.Data.GetItems(toCategory)

    for i, item in ipairs(fromList) do
        if item.id == id then
            local movingItem = table.remove(fromList, i)
            movingItem.completed = false
            table.insert(toList, movingItem)
            return true
        end
    end
    return false
end

function DetaurBar.Data.SavePricePoint(itemId, buyoutPerItem)
    DetaurBar.Data.InitializeDB()
    local faction = UnitFactionGroup("player") or "Unknown"
    local key = itemId .. ":" .. faction
    if not DetaurBarDB.priceHistory[key] then
        DetaurBarDB.priceHistory[key] = {}
    end
    DetaurBarDB.priceHistory[key][tostring(time())] = buyoutPerItem
end

function DetaurBar.Data.GetPriceHistory(itemId)
    DetaurBar.Data.InitializeDB()
    local faction = UnitFactionGroup("player") or "Unknown"
    local key = itemId .. ":" .. faction
    return DetaurBarDB.priceHistory[key] or {}
end

function DetaurBar.Data.GetBuySellHistory(itemId)
    DetaurBar.Data.InitializeDB()
    local faction = UnitFactionGroup("player") or "Unknown"
    local key = itemId .. ":" .. faction
    local raw = DetaurBarDB.buySellHistory[key]
    if not raw then return {} end
    local result = {}
    for _, record in ipairs(raw) do
        table.insert(result, record)
    end
    table.sort(result, function(a, b) return a.ts < b.ts end)
    return result
end

function DetaurBar.Data.IsItemInPriceList(itemId)
    DetaurBar.Data.InitializeDB()
    local faction = UnitFactionGroup("player") or "Unknown"
    local items = DetaurBarDB.price[faction]
    if not items then return false end
    local prefix = "item:" .. itemId
    for _, item in ipairs(items) do
        if item.title == prefix then return true end
    end
    return false
end

function DetaurBar.Data.RecordBuyTransaction(itemId, pricePerItem, quantity, timestamp)
    DetaurBar.Data.InitializeDB()
    if pricePerItem == 0 then
        local history = DetaurBar.Data.GetPriceHistory(itemId)
        local maxTs = 0
        for tsStr, price in pairs(history) do
            local ts = tonumber(tsStr)
            if ts and ts > maxTs then
                maxTs = ts
                pricePerItem = price
            end
        end
    end
    local faction = UnitFactionGroup("player") or "Unknown"
    local key = itemId .. ":" .. faction
    if not DetaurBarDB.buySellHistory[key] then
        DetaurBarDB.buySellHistory[key] = {}
    end
    table.insert(DetaurBarDB.buySellHistory[key], {
        ts = timestamp or time(),
        type = "buy",
        price = pricePerItem,
        quantity = quantity or 1,
    })
end

function DetaurBar.Data.RecordSellTransaction(itemId, pricePerItem, quantity, timestamp)
    DetaurBar.Data.InitializeDB()
    local faction = UnitFactionGroup("player") or "Unknown"
    local key = itemId .. ":" .. faction
    if not DetaurBarDB.buySellHistory[key] then
        DetaurBarDB.buySellHistory[key] = {}
    end
    table.insert(DetaurBarDB.buySellHistory[key], {
        ts = timestamp or time(),
        type = "sell",
        price = pricePerItem,
        quantity = quantity or 1,
    })
end

function DetaurBar.Data.DeletePricePoint(itemId, timestampStr)
    DetaurBar.Data.InitializeDB()
    local faction = UnitFactionGroup("player") or "Unknown"
    local key = itemId .. ":" .. faction
    DEFAULT_CHAT_FRAME:AddMessage("|cff888888[DEBUG] Delete: itemId=" .. tostring(itemId) .. " (" .. type(itemId) .. "), key=" .. tostring(key) .. ", ts=" .. tostring(timestampStr))
    if DetaurBarDB.priceHistory[key] then
        local before = DetaurBarDB.priceHistory[key][timestampStr]
        DetaurBarDB.priceHistory[key][timestampStr] = nil
        local after = DetaurBarDB.priceHistory[key][timestampStr]
        DEFAULT_CHAT_FRAME:AddMessage("|cff888888[DEBUG] before=" .. tostring(before) .. ", after=" .. tostring(after))
    else
        DEFAULT_CHAT_FRAME:AddMessage("|cffff0000[DEBUG] key not found: " .. tostring(key))
    end
end

function DetaurBar.Data.GetSettings()
    DetaurBar.Data.InitializeDB()
    return DetaurBarDB.settings
end

function DetaurBar.Data.IsSubTabVisible(tabType, subTabName)
    local settings = DetaurBar.Data.GetSettings()
    if tabType == "loot" then
        return settings.lootSubTabsVisible and settings.lootSubTabsVisible[subTabName] ~= false
    elseif tabType == "price" then
        return settings.priceSubTabsVisible and settings.priceSubTabsVisible[subTabName] ~= false
    elseif tabType == "alert" then
        return settings.alertSubTabsVisible and settings.alertSubTabsVisible[subTabName] ~= false
    end
    return true
end

function DetaurBar.Data.GetItemName(itemId)
    if not itemId then return nil end
    if DetaurBar.Data.ItemDatabaseReverse and DetaurBar.Data.ItemDatabaseReverse[itemId] then
        local name = DetaurBar.Data.ItemDatabaseReverse[itemId]
        return (name:sub(1,1):upper() .. name:sub(2)):gsub("(%s)(%a)", function(s, a) return s .. a:upper() end)
    end
    return (GetItemInfo(itemId))
end

-- Icon caching: tries static ItemIcons -> DetaurBarDB.iconCache -> GetItemInfo
-- If GetItemInfo succeeds, stores result in DB for next reload.
function DetaurBar.Data.GetItemTexture(itemId)
    if not itemId then return nil end
    if DetaurBar.Data.ItemIcons and DetaurBar.Data.ItemIcons[itemId] then
        return DetaurBar.Data.ItemIcons[itemId]
    end
    DetaurBar.Data.InitializeDB()
    if DetaurBarDB.iconCache and DetaurBarDB.iconCache[itemId] then
        return DetaurBarDB.iconCache[itemId]
    end
    local texture = select(10, GetItemInfo(itemId))
    if texture then
        if not DetaurBarDB.iconCache then DetaurBarDB.iconCache = {} end
        DetaurBarDB.iconCache[itemId] = texture
    end
    return texture
end

function DetaurBar.Data.GetRandomAlerts()
    DetaurBar.Data.InitializeDB()
    return DetaurBarDB.settings.randomAlerts or {}
end

function DetaurBar.Data.AddRandomAlert(name)
    DetaurBar.Data.InitializeDB()
    local alert = {
        id = tostring(time()) .. "_" .. tostring(math.random(1000, 9999)),
        name = name or "New Alert",
        intervalMinutes = 5,
        flashDuration = 3,
        flashColor = "YELLOW",
        playSound = false,
        sound = "RaidWarning",
    }
    table.insert(DetaurBarDB.settings.randomAlerts, alert)
    return alert
end

function DetaurBar.Data.DeleteRandomAlert(id)
    DetaurBar.Data.InitializeDB()
    local alerts = DetaurBarDB.settings.randomAlerts
    for i, alert in ipairs(alerts) do
        if alert.id == id then
            table.remove(alerts, i)
            if DetaurBarDB.settings.randomActiveAlertId == id then
                DetaurBarDB.settings.randomActiveAlertId = alerts[1] and alerts[1].id or nil
            end
            return true
        end
    end
    return false
end

function DetaurBar.Data.GetRandomActiveAlert()
    DetaurBar.Data.InitializeDB()
    local id = DetaurBarDB.settings.randomActiveAlertId
    if not id then return nil end
    for _, alert in ipairs(DetaurBarDB.settings.randomAlerts) do
        if alert.id == id then return alert end
    end
    return nil
end

function DetaurBar.Data.SetRandomActiveAlert(id)
    DetaurBar.Data.InitializeDB()
    DetaurBarDB.settings.randomActiveAlertId = id
end

function DetaurBar.Data.GetNoteCategories()
    DetaurBar.Data.InitializeDB()
    return DetaurBarDB.notes.categories
end

function DetaurBar.Data.NoteCategoryExists(name)
    DetaurBar.Data.InitializeDB()
    if not name then return false end
    for _, cat in ipairs(DetaurBarDB.notes.categories) do
        if cat == name then return true end
    end
    return false
end

function DetaurBar.Data.AddNoteCategory(name)
    DetaurBar.Data.InitializeDB()
    name = name:gsub("^%s*(.-)%s*$", "%1")
    if name == "" then return nil end
    for _, cat in ipairs(DetaurBarDB.notes.categories) do
        if cat:lower() == name:lower() then return nil end
    end
    table.insert(DetaurBarDB.notes.categories, name)
    DetaurBarDB.notes.data[name] = {}
    return name
end

function DetaurBar.Data.DeleteNoteCategory(name)
    DetaurBar.Data.InitializeDB()
    if #DetaurBarDB.notes.categories <= 1 then return false end
    for i, cat in ipairs(DetaurBarDB.notes.categories) do
        if cat == name then
            table.remove(DetaurBarDB.notes.categories, i)
            DetaurBarDB.notes.data[name] = nil
            return true
        end
    end
    return false
end

function DetaurBar.Data.GetTaskCategories()
    DetaurBar.Data.InitializeDB()
    return DetaurBarDB.tasks.categories
end

function DetaurBar.Data.TaskCategoryExists(name)
    DetaurBar.Data.InitializeDB()
    if not name then return false end
    for _, cat in ipairs(DetaurBarDB.tasks.categories) do
        if cat == name then return true end
    end
    return false
end

function DetaurBar.Data.AddTaskCategory(name)
    DetaurBar.Data.InitializeDB()
    name = name:gsub("^%s*(.-)%s*$", "%1")
    if name == "" then return nil end
    for _, cat in ipairs(DetaurBarDB.tasks.categories) do
        if cat:lower() == name:lower() then return nil end
    end
    table.insert(DetaurBarDB.tasks.categories, name)
    DetaurBarDB.tasks.data[name] = {}
    return name
end

function DetaurBar.Data.DeleteTaskCategory(name)
    DetaurBar.Data.InitializeDB()
    if not name or name:lower() == "general" then return false end
    if #DetaurBarDB.tasks.categories <= 1 then return false end
    for i, cat in ipairs(DetaurBarDB.tasks.categories) do
        if cat:lower() == name:lower() then
            table.remove(DetaurBarDB.tasks.categories, i)
            DetaurBarDB.tasks.data[cat] = nil
            return true
        end
    end
    return false
end
